Repository LawDigest/LawDigest-FE, pull requests merged in 2023-12, with the labels that each got.

#2 [feat] #2 프로젝트 초기 설정
  app/layout.tsx
  app/page.tsx
  components/common/Header/Header.tsx
  components/common/Header/index.tsx
  components/common/Nav/Nav.tsx
  components/common/Nav/NavIcons.tsx
  components/common/Nav/index.tsx
  components/navbar.tsx
  config/site.ts
  package.json
  pnpm-lock.yaml
  public/next.svg
  public/vercel.svg
Labels: enhancement, feature

#6 [feat] #6 타임라인 페이지 구현
  .npmrc
  app/components/BillNav.tsx
  app/components/index.tsx
  app/docs/layout.tsx
  app/docs/page.tsx
  app/index.tsx
  app/layout.tsx
  app/page.tsx
  app/pricing/layout.tsx
  app/pricing/page.tsx
  components/Bill/Feed/Feed.tsx
  components/Bill/Feed/index.tsx
  components/common/SearchBar/SearchBar.tsx
  components/common/SearchBar/SearchIcon.tsx
  components/common/SearchBar/index.tsx
  components/counter.tsx
  components/icons.tsx
  components/primitives.ts
  config/site.ts
  package.json
  pnpm-lock.yaml
  public/images/logo.png
Labels: feature

#5 [feat] #4 통계 페이지 퍼블리싱
  app/page.tsx
  app/statistics/components/CardItem.tsx
  app/statistics/components/keyword/Keyword.tsx
  app/statistics/components/member/MemberItem.tsx
  app/statistics/components/member/MemberList.tsx
  app/statistics/components/party/Party.tsx
  app/statistics/components/party/PartyContainer.tsx
  app/statistics/components/seat/Seat.tsx
  app/statistics/page.tsx
  package-lock.json
  public/mock/국민의힘_로고.svg
  public/mock/국민의힘_로고_원.svg
  public/mock/국회_의석수_현황.svg
  public/mock/기본소득당_로고.svg
  public/mock/더불어민주당_로고.svg
  public/mock/더불어민주당_로고_원.svg
  public/mock/사용자_프로필.svg
  public/mock/정의당_로고.svg
  public/mock/정의당_로고_원.svg
  public/mock/주요_키워드_이미지.svg
Labels: enhancement, feature

#10 [feat] #10 무한 스크롤 구현
  .eslintrc.json
  .gitignore
  api/config/core.ts
  app/about/layout.tsx
  app/about/page.tsx
  app/bill/[id]/apis/api.ts
  app/bill/[id]/apis/index.ts
  app/bill/[id]/apis/queries.ts
  app/bill/[id]/apis/type.ts
  app/bill/[id]/components/Chart/Chart.tsx
  app/bill/[id]/components/Chart/index.tsx
  app/bill/[id]/components/Keywords/Keywords.tsx
  app/bill/[id]/components/Keywords/index.tsx
  app/bill/[id]/components/Similars/Similars.tsx
  app/bill/[id]/components/Similars/indext.tsx
  app/bill/[id]/components/Steps/Steps.tsx
  app/bill/[id]/components/Steps/index.tsx
  app/bill/[id]/layout.tsx
  app/bill/[id]/page.tsx
  app/blog/layout.tsx
  app/blog/page.tsx
  app/components/Feed/apis.ts
  app/components/Feed/hooks/index.ts
  app/components/Feed/hooks/useFetchBills.ts
  app/components/Feed/hooks/useIntersect.ts
  app/components/Feed/index.tsx
  app/components/Feed/types.ts
  app/components/index.tsx
  app/getQueryClient.tsx
  app/layout.tsx
  app/lib/providers.tsx
  app/lib/query.tsx
  app/page.tsx
  components/Bill/Bill.tsx
  components/Bill/Feed/Feed.tsx
  components/Bill/Feed/index.tsx
  components/Bill/index.tsx
  components/Bill/type.ts
  components/CardFooter/CardFooter.tsx
  components/CardFooter/index.tsx
  components/GPTSummary/GPTSummary.tsx
  components/GPTSummary/index.tsx
  components/common/SearchBar/SearchIcon.tsx
  components/common/icons.tsx
  components/theme-switch.tsx
  constants/api.ts
  constants/bill.ts
  constants/index.ts
  constants/theme.ts
  package.json
  pnpm-lock.yaml
  public/favicon.ico
  public/images/gpt.png
  public/images/logo.png
  tailwind.config.js
  tsconfig.json
  types/icon.ts
  types/index.ts
  types/type/api.ts
  types/type/index.ts
Labels: enhancement, feature

#12 [fix] #11 로고 이미지 추가
  pnpm-lock.yaml
  public/images/logo.png
Labels: bug

#18 [feat] #13 통계 페이지 기능 추가
  app/layout.tsx
  app/statistics/components/member/MemberItem.tsx
  app/statistics/components/party/Party.tsx
  app/statistics/components/party/PartyContainer.tsx
  package.json
  pnpm-lock.yaml
  styles/globals.css
Labels: enhancement, feature

#20 [feat] #20 무한 스크롤 api 연결
  api/config/core.ts
  app/bill/[id]/page.tsx
  app/components/Feed/apis.ts
  app/components/Feed/hooks/useFetchBills.ts
  app/components/Feed/index.tsx
  app/components/Feed/types.ts
  app/error.tsx
  app/layout.tsx
  app/page.tsx
  components/Bill/Bill.tsx
  components/Bill/type.ts
  package.json
  pnpm-lock.yaml
  public/images/logo.png
  styles/globals.css
  types/type/api.ts
Labels: enhancement, feature

#19 [feat] #17 알림 페이지 퍼블리싱
  app/notification/conponents/Item.tsx
  app/notification/conponents/ItemList.tsx
  app/notification/page.tsx
  lib/timeRemaining.ts
  public/images/arrow_right.svg
Labels: feature

#23 [feat] #22 의안 상세, 정당 페이지 구현, 무한 스크롤 API 고도화
  .eslintrc.json
  app/bill/[id]/apis/api.ts
  app/bill/[id]/apis/queries.ts
  app/bill/[id]/apis/type.ts
  app/bill/[id]/components/Keywords/Keywords.tsx
  app/bill/[id]/page.tsx
  app/components/BillNav.tsx
  app/components/Feed/apis.ts
  app/components/Feed/hooks/index.ts
  app/components/Feed/index.tsx
  app/congressman/[id]/apis/api.ts
  app/congressman/[id]/apis/index.ts
  app/congressman/[id]/apis/queries.ts
  app/congressman/[id]/page.tsx
  app/congressman/[id]/types.ts
  app/error.tsx
  app/layout.tsx
  app/lib/providers.tsx
  app/page.tsx
  app/party/[id]/apis/api.ts
  app/party/[id]/apis/index.ts
  app/party/[id]/apis/queries.ts
  app/party/[id]/page.tsx
  components/Bill/Bill.tsx
  components/BillTab/BillTab.tsx
  components/BillTab/index.tsx
  components/CardFooter/CardFooter.tsx
  components/common/Icons/Common.tsx
  components/common/Icons/Party.tsx
  components/common/Icons/index.tsx
  config/site.ts
  constants/bill.ts
  hooks/index.ts
  hooks/useGetBills.ts
  hooks/useIntersect.ts
  hooks/useTabType.ts
  next.config.js
  package.json
  pnpm-lock.yaml
  public/images/keyword.png
  public/images/logo/국민의힘.svg
  public/images/logo/더불어민주당.svg
  public/images/logo/정의당.svg
  tsconfig.json
  types/helper.ts
  types/index.ts
  types/type/bill.ts
  types/type/common.ts
  types/type/index.ts
Labels: feature

#25 [feat] #25 의원 상세페이지 api 연결
  .eslintrc.json
  app/bill/[id]/apis/type.ts
  app/bill/[id]/components/Chart/Chart.tsx
  app/bill/[id]/components/Keywords/Keywords.tsx
  app/bill/[id]/components/Stages/Stages.tsx
  app/bill/[id]/components/Stages/index.tsx
  app/bill/[id]/components/Steps/index.tsx
  app/bill/[id]/page.tsx
  app/components/Feed/index.tsx
  app/congressman/[id]/Congressman/Congressman.tsx
  app/congressman/[id]/Congressman/index.tsx
  app/congressman/[id]/apis/api.ts
  app/congressman/[id]/apis/queries.ts
  app/congressman/[id]/page.tsx
  app/layout.tsx
  app/party/[id]/apis/api.ts
  app/party/[id]/apis/queries.ts
  app/party/[id]/page.tsx
  components/Bill/BillList/Bill/Bill.tsx
  components/Bill/BillList/Bill/index.tsx
  components/Bill/BillList/BillList.tsx
  components/Bill/BillList/index.tsx
  components/Bill/BillTab/BillTab.tsx
  components/Bill/BillTab/index.tsx
  components/Bill/index.tsx
  components/GPTSummary/GPTSummary.tsx
  components/Proposers/Proposers.tsx
  components/Proposers/index.tsx
  components/common/Header/Header.tsx
  components/common/Icons/Party.tsx
  constants/theme.ts
  next.config.js
  pnpm-lock.yaml
  styles/globals.css
  types/type/bill.ts
  types/type/congressman.ts
  types/type/index.ts
  types/type/party.ts
Labels: enhancement, feature

#28 [feat] #28 로그인 페이지 목업
  .eslintrc.json
  app/bill/[id]/layout.tsx
  app/congressman/[id]/layout.tsx
  app/layout.tsx
  app/login/layout.tsx
  app/login/page.tsx
  app/notification/layout.tsx
  app/page.tsx
  app/party/[id]/layout.tsx
  app/party/[id]/page.tsx
  app/search/layout.tsx
  app/signup/layout.tsx
  app/signup/page.tsx
  app/statistics/layout.tsx
  components/common/Header/Header.tsx
  components/common/Layout/index.tsx
  components/common/Nav/NavIcons.tsx
Labels: enhancement, feature

#26 [feat] #22 마이 피드 페이지 퍼블리싱
  app/mypage/components/Follow/FollowItem.tsx
  app/mypage/components/Follow/index.tsx
  app/mypage/page.tsx
  app/notification/components/Item/Item.tsx
  app/notification/components/Item/ItemList.tsx
  app/notification/components/Item/index.tsx
  app/notification/page.tsx
  app/search/components/Card/CardItem.tsx
  app/search/components/Card/index.tsx
  app/search/components/LawList/index.tsx
  app/search/components/keyword/index.tsx
  app/search/page.tsx
  app/statistics/components/Card/CardItem.tsx
  app/statistics/components/Card/index.tsx
  app/statistics/components/keyword/Keyword.tsx
  app/statistics/components/member/index.tsx
  app/statistics/components/party/index.tsx
  app/statistics/components/seat/Seat.tsx
  app/statistics/page.tsx
  pnpm-lock.yaml
  tailwind.config.js
  utils/getTimeRemaining.ts
Labels: feature
